comp:
	g++ src/*.cpp -o output -I/usr/include/libxml2/ -I/usr/local/include/libfreenect2/ -I/usr/include/libfreenect2/ -I/usr/local/include/ -I/usr/include/ -lpthread -lxml2   -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_flann -lopencv_imgcodecs -lopencv_videoio
